-- MVP economy v2: usage totals + generation audit (run after supabase_mvp_credits.sql)

ALTER TABLE users ADD COLUMN IF NOT EXISTS total_generated_seconds integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS generation_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id bigint NOT NULL,
  text_length integer NOT NULL DEFAULT 0,
  voice_id text NOT NULL DEFAULT '',
  generation_duration_credits integer NOT NULL DEFAULT 0,
  estimated_seconds integer NOT NULL DEFAULT 0,
  status text NOT NULL CHECK (status IN ('completed', 'failed')),
  failure_reason text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS generation_logs_telegram_idx ON generation_logs (telegram_id);
CREATE INDEX IF NOT EXISTS generation_logs_created_idx ON generation_logs (created_at);

-- Optional: Stars ledger (mirror successful payments; populated from app logic if extended)
CREATE TABLE IF NOT EXISTS stars_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  telegram_id bigint NOT NULL,
  stars_payment_id text NULL,
  credits_added integer NOT NULL DEFAULT 0,
  purchase_type text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
