-- VoiceStudio Pro MVP: credits economy + analytics (run in Supabase SQL editor)

-- Users: credit balances & free-tier tracking
ALTER TABLE users ADD COLUMN IF NOT EXISTS credit_balance integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_credit_balance integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_credits_reset_at timestamptz NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_seconds_used integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_generation_count integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_gen_count integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_gen_date date NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_generate_at timestamptz NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_generate_fingerprint text NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_streak_days integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_streak_date date NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_daily_bonus_date date NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_paid_at timestamptz NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_generation_at timestamptz NULL;

-- Extend invoice product types for credit top-ups
ALTER TABLE stars_invoices DROP CONSTRAINT IF EXISTS stars_invoices_product_type_check;

-- Analytics funnel (optional failures are handled in backend)
CREATE TABLE IF NOT EXISTS analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id bigint NOT NULL,
  event text NOT NULL,
  props jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS analytics_events_event_idx ON analytics_events (event);

-- Referrals
CREATE TABLE IF NOT EXISTS referrals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_telegram_id bigint NOT NULL,
  invitee_telegram_id bigint NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);
